---
version: '3.8'
services:

  metrics_exporter:
    container_name: metrics_exporter
    image: metrics_exporter
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - PING_TARGETS=1.1.1.1,www.google.com
        - DISK_TYPES_TO_MONITOR=sd,nvme
    volumes:
      - '/:/hostfs:ro'
    ports:
      - 8000:8000
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.1.0@sha256:6559acbd5d770b15bb3c954629ce190ac3cbbdb2b7f1c30f0385c4e05104e218
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    healthcheck:
      test: wget -q http://localhost:9090 -O index_check.html || exit 1
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      - metrics_exporter

  grafana:
    image: grafana/grafana:11.4.0@sha256:d8ea37798ccc41061a62ab080f2676dda6bf7815558499f901bdb0f533a456fb
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - graf_data:/var/lib/grafana
      - ./grafana/data_sources.yml:/etc/grafana/provisioning/datasources/DataSources.yaml
      - ./grafana/dashboard_sources.yml:/etc/grafana/provisioning/dashboards/DashboardSources.yaml
      - ./grafana/dashboard.json:/etc/grafana/initialDashboards/dashboard.json
    healthcheck:
      test: curl http://localhost:3000/api/health || exit 1
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prom_data:
    name: custom_metrics_prom_data
  graf_data:
    name: custom_metrics_grafana_data
