---
version: '3.8'
services:

  metrics_exporter:
    container_name: metrics_exporter
    image: metrics_exporter
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - PING_TARGETS=1.1.1.1,www.google.com
        - DISK_TYPES_TO_MONITOR=sd,nvme
    volumes:
      - '/:/hostfs:ro'
    ports:
      - 8000:8000
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.55.0@sha256:378f4e03703557d1c6419e6caccf922f96e6d88a530f7431d66a4c4f4b1000fe
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    healthcheck:
      test: wget -q http://localhost:9090 -O index_check.html || exit 1
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      - metrics_exporter

  grafana:
    image: grafana/grafana:11.3.0@sha256:a0f881232a6fb71a0554a47d0fe2203b6888fe77f4cefb7ea62bed7eb54e13c3
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - graf_data:/var/lib/grafana
      - ./grafana/data_sources.yml:/etc/grafana/provisioning/datasources/DataSources.yaml
      - ./grafana/dashboard_sources.yml:/etc/grafana/provisioning/dashboards/DashboardSources.yaml
      - ./grafana/dashboard.json:/etc/grafana/initialDashboards/dashboard.json
    healthcheck:
      test: curl http://localhost:3000/api/health || exit 1
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prom_data:
    name: custom_metrics_prom_data
  graf_data:
    name: custom_metrics_grafana_data
