---
version: '3.8'
services:

  metrics_exporter:
    container_name: metrics_exporter
    image: metrics_exporter
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - PING_TARGETS=1.1.1.1,www.google.com
        - DISK_TYPES_TO_MONITOR=sd,nvme
    volumes:
      - '/:/hostfs:ro'
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus@sha256:5c435642ca4d8427ca26f4901c11114023004709037880cd7860d5b7176aa731
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    depends_on:
      - metrics_exporter

  grafana:
    image: grafana/grafana@sha256:0dc5a246ab16bb2c38a349fb588174e832b4c6c2db0981d0c3e6cd774ba66a54
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - graf_data:/var/lib/grafana
      - ./grafana/data_sources.yml:/etc/grafana/provisioning/datasources/DataSources.yaml
      - ./grafana/dashboard_sources.yml:/etc/grafana/provisioning/dashboards/DashboardSources.yaml
      - ./grafana/dashboard.json:/etc/grafana/initialDashboards/dashboard.json
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prom_data:
    name: custom_metrics_prom_data
  graf_data:
    name: custom_metrics_grafana_data
