---
name: Dry-run
run-name: Commit on branch ${{ github.ref_name }} by @${{ github.actor }}
    
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, edited, reopened]
  workflow_dispatch:
    
jobs:
  Dry-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install Compose
        uses: ndeloof/install-compose-action@4a33bc31f327b8231c4f343f6fba704fedc0fa23 # v0.0.1
        with:
          version: 'latest'
          legacy: true    # will also install in PATH as `docker-compose`
      - name: Run docker-compose
        run: docker-compose up -d --build
      - name: Print running containers
        run: |
          sleep 20
          docker ps -a
      - name: Run reachability testing script
        run: |
          ./.github/tests/reachability_tests.sh
